repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.0
  hooks:
    - id: ruff-check
      exclude: ^example-notebooks/
      args: [--config=ruff.toml]
    - id: ruff-format
      exclude: ^example-notebooks/

- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
    - id: nbstripout
      exclude: ^example-notebooks/
