include = [
    "pyproject.toml",
    "src/tlc_tools/**/*.py",
    "tests/**/*.py",
]

exclude = [
    "example-notebooks/",
]

line-length = 120
indent-width = 4
target-version = "py39"

[lint]
select = [
    "B",
    "E",
    "F",
    "UP",
    "SIM",
    "I",
]

[lint.isort]
known-first-party = ["tlc"]