#!/usr/bin/env python3
"""Single source of truth for notebook metadata: ``tutorials/notebooks.yaml``.

Every example notebook has one entry in ``tutorials/notebooks.yaml``. An entry has two
kinds of fields:

- **Derived** (``title``, ``blurb``, ``tags``, ``thumbnail``, ``project_meta``): extracted
  from the notebook itself. These are regenerated by ``sync`` and must never be hand-edited
  -- ``check`` fails CI when they drift from the notebook content.
- **Curated** (``include_in_docs``, ``include_in_tests``, ``include_in_public_examples``,
  ``params``, ``depends_on``): hand-maintained and preserved across ``sync``.

Commands::

    python -m utils.notebooks_metadata sync      # regenerate derived fields, preserve curated
    python -m utils.notebooks_metadata check      # fail if derived fields drift from notebooks
    python -m utils.notebooks_metadata migrate ...  # one-shot build from legacy sources

The monorepo consumes ``tutorials/notebooks.yaml`` directly (it is fetched along with the
``tutorials`` tree); it does not import this module.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.parse
from pathlib import Path
from typing import Any

import yaml

# Fields extracted from notebook content (regenerated by `sync`).
DERIVED_FIELDS = ("title", "blurb", "tags", "thumbnail", "project_meta")

# Curated fields and their defaults for new notebooks (preserved across `sync`).
CURATED_DEFAULTS: dict[str, Any] = {
    "include_in_docs": True,
    "include_in_tests": False,
    "include_in_public_examples": False,
    "params": {},
    "depends_on": [],
}

# Canonical key order within a single notebook entry (derived first, then curated).
ENTRY_KEY_ORDER = [
    "path",
    *DERIVED_FIELDS,
    "include_in_docs",
    "include_in_tests",
    "include_in_public_examples",
    "params",
    "depends_on",
]

DASHBOARD_URL = "https://dashboard.3lc.ai"
PROJECT_ROOT_URL = "s3://3lc-public-examples-2-2-dev"


# --- Metadata extraction (ported from tlc-monorepo/utils/generate_notebooks_json.py) -------


def normalize_tag(tag: str) -> str:
    """Normalize a tag to a canonical lowercase, hyphen-separated form.

    Examples:
        "Image Classification" -> "image-classification"
        "image_classification" -> "image-classification"

    Args:
        tag: Raw tag string.

    Returns:
        Normalized tag string.

    """
    normalized = tag.lower().strip()
    normalized = re.sub(r"[\s_]+", "-", normalized)
    normalized = re.sub(r"-+", "-", normalized)
    return normalized.strip("-")


def extract_project_meta_from_parameters_cell(parameters_cell_source: str) -> dict[str, Any]:
    """Extract project/dataset/run/table names and a dashboard URL from a parameters cell."""
    project_match = re.search(r'(?m)^\s*PROJECT_NAME\s*=\s*"([^"]+)"', parameters_cell_source)
    dataset_match = re.search(r'(?m)^\s*DATASET_NAME\s*=\s*"([^"]+)"', parameters_cell_source)
    run_name_match = re.search(r'(?m)^\s*RUN_NAME\s*=\s*"([^"]+)"', parameters_cell_source)
    table_name_match = re.search(r'(?m)^\s*TABLE_NAME\s*=\s*"([^"]+)"', parameters_cell_source)

    project_meta: dict[str, Any] = {
        "project_name": project_match.group(1) if project_match else None,
        "dataset_name": dataset_match.group(1) if dataset_match else None,
        "run_name": run_name_match.group(1) if run_name_match else None,
        "table_name": table_name_match.group(1) if table_name_match else None,
        "object_url": None,
    }

    if project_meta["project_name"] and project_meta["run_name"]:
        run_url = f"{PROJECT_ROOT_URL}/projects/{project_meta['project_name']}/runs/{project_meta['run_name']}"
        project_meta["object_url"] = f"{DASHBOARD_URL}?runs={urllib.parse.quote(run_url)}"

    if project_meta["project_name"] and project_meta["dataset_name"] and project_meta["table_name"]:
        table_url = (
            f"{PROJECT_ROOT_URL}/projects/{project_meta['project_name']}"
            f"/datasets/{project_meta['dataset_name']}/tables/{project_meta['table_name']}"
        )
        project_meta["object_url"] = f"{DASHBOARD_URL}?tables={urllib.parse.quote(table_url)}"

    return project_meta


def extract_metadata_from_notebook(notebook_path: Path) -> dict[str, Any]:  # noqa: C901
    """Extract derived metadata from a single notebook.

    Assumptions:
    - The first cell is a markdown cell containing the title (first heading), blurb (following
      text), thumbnail (first image) and tags (an ``<!-- Tags: [...] -->`` HTML comment).
    - There is at most one parameters cell (a code cell tagged ``parameters``).

    Args:
        notebook_path: Path to the ``.ipynb`` file.

    Returns:
        Dictionary with keys: ``title``, ``tags``, ``blurb``, ``thumbnail``, ``project_meta``.

    """
    metadata: dict[str, Any] = {
        "title": "",
        "tags": [],
        "blurb": "",
        "thumbnail": "",
        "project_meta": {},
    }

    try:
        with open(notebook_path, encoding="utf-8") as f:
            nb_data = json.load(f)

        cells = nb_data.get("cells", [])

        # 1) First markdown cell (assumed to be cells[0]).
        if cells and isinstance(cells[0], dict) and cells[0].get("cell_type") == "markdown":
            source = cells[0].get("source", [])
            source_text = "".join(source) if isinstance(source, list) else source
            lines = source_text.split("\n")

            # Tags from HTML comment in first markdown cell.
            for line in lines:
                tags_match = re.search(r"<!--\s*Tags:\s*\[(.*?)\]\s*-->", line, re.IGNORECASE)
                if tags_match:
                    tags_str = tags_match.group(1)
                    metadata["tags"] = [
                        normalize_tag(tag.strip().strip("'\"")) for tag in tags_str.split(",") if tag.strip()
                    ]
                    break

            # Title from first heading line, blurb from the lines that follow.
            title_found = False
            blurb_lines: list[str] = []
            collecting_blurb = False
            for line in lines:
                stripped = line.strip()
                if stripped.startswith("<!--"):
                    continue
                if not title_found and stripped.startswith("#"):
                    title = re.sub(r"^#+\s*", "", stripped).strip()
                    if title:
                        metadata["title"] = title
                        title_found = True
                        collecting_blurb = True
                    continue
                if collecting_blurb:
                    if stripped.startswith(("#", "![")):
                        break
                    if not stripped:
                        if blurb_lines:
                            break
                        continue
                    blurb_lines.append(stripped)
            if blurb_lines:
                blurb = " ".join(blurb_lines)
                if len(blurb) > 200:
                    blurb = blurb[:197] + "..."
                metadata["blurb"] = blurb

            # Thumbnail from first image in first markdown cell.
            for line in lines:
                img_match = re.search(r"!\[.*?\]\((.*?)\)", line)
                if img_match:
                    metadata["thumbnail"] = img_match.group(1).strip()
                    break

        # 2) Parameters cell (Papermill convention).
        try:
            for cell in cells:
                if cell.get("cell_type") != "code":
                    continue
                cell_meta = cell.get("metadata", {}) or {}
                tags = cell_meta.get("tags", []) or []
                if any(isinstance(t, str) and t.strip().lower() == "parameters" for t in tags):
                    src = cell.get("source", "")
                    parameters_cell_source = "".join(src) if isinstance(src, list) else (src or "")
                    metadata["project_meta"] = extract_project_meta_from_parameters_cell(parameters_cell_source)
                    break
        except Exception:  # noqa: BLE001 - parameters cell is best-effort
            pass

    except Exception as e:  # noqa: BLE001 - never let a single bad notebook abort the scan
        print(f"Warning: Could not extract metadata from {notebook_path}: {e}", file=sys.stderr)

    if not metadata["title"]:
        metadata["title"] = notebook_path.stem.replace("-", " ").replace("_", " ").title()

    return metadata


def _resolve_thumbnail(thumbnail: str, notebook_path: Path, tutorials_dir: Path) -> str:
    """Re-relativize a notebook-relative thumbnail path to be relative to ``tutorials_dir``."""
    if not thumbnail:
        return ""
    thumbnail_absolute = (notebook_path.parent / thumbnail).resolve()
    try:
        return thumbnail_absolute.relative_to(tutorials_dir.resolve()).as_posix()
    except ValueError:
        print(
            f"  Warning: Thumbnail {thumbnail} in {notebook_path} is outside the tutorials directory",
            file=sys.stderr,
        )
        return thumbnail


def iter_notebook_paths(tutorials_dir: Path) -> list[Path]:
    """Return notebook paths in deterministic depth-first, lexicographic order."""
    ordered: list[Path] = []

    def traverse(directory: Path) -> None:
        try:
            children = sorted(directory.iterdir(), key=lambda p: p.name.lower())
        except Exception as e:  # noqa: BLE001
            print(f"Warning: Could not list directory {directory}: {e}", file=sys.stderr)
            return
        for child in children:
            if child.name.startswith("."):
                continue
            if child.is_file():
                if child.suffix == ".ipynb":
                    ordered.append(child)
            elif child.is_dir():
                traverse(child)

    traverse(tutorials_dir)
    return ordered


def derived_entry_for(notebook_path: Path, tutorials_dir: Path) -> dict[str, Any]:
    """Build the derived (path + extracted) fields for a single notebook."""
    nb = extract_metadata_from_notebook(notebook_path)
    return {
        "path": notebook_path.relative_to(tutorials_dir).as_posix(),
        "title": nb["title"],
        "blurb": nb["blurb"],
        "tags": nb["tags"],
        "thumbnail": _resolve_thumbnail(nb["thumbnail"], notebook_path, tutorials_dir),
        "project_meta": nb.get("project_meta", {}),
    }


def build_derived_entries(tutorials_dir: Path) -> list[dict[str, Any]]:
    """Extract derived metadata for every notebook under ``tutorials_dir``, in canonical order."""
    return [derived_entry_for(p, tutorials_dir) for p in iter_notebook_paths(tutorials_dir)]


# --- YAML (de)serialization ----------------------------------------------------------------


class _FlowSeq(list):
    """A list rendered in flow style, e.g. ``[a, b]``."""


class _FlowMap(dict):
    """A mapping rendered in flow style, e.g. ``{test: 1, publish: 5}``."""


class _NotebooksDumper(yaml.SafeDumper):
    """SafeDumper that keeps key order and renders tags / param values inline."""


def _represent_flow_seq(dumper: yaml.Dumper, data: _FlowSeq) -> yaml.Node:
    return dumper.represent_sequence("tag:yaml.org,2002:seq", data, flow_style=True)


def _represent_flow_map(dumper: yaml.Dumper, data: _FlowMap) -> yaml.Node:
    return dumper.represent_mapping("tag:yaml.org,2002:map", data, flow_style=True)


_NotebooksDumper.add_representer(_FlowSeq, _represent_flow_seq)
_NotebooksDumper.add_representer(_FlowMap, _represent_flow_map)

HEADER = """\
# Single source of truth for example notebook metadata.
#
# DERIVED fields (title, blurb, tags, thumbnail, project_meta) are extracted from the
# notebooks themselves -- do NOT edit them by hand. Regenerate with:
#     python -m utils.notebooks_metadata sync
# CI (`... check`) fails if they drift from notebook content.
#
# CURATED fields (include_in_docs/tests/public_examples, params, depends_on) are
# hand-maintained here and preserved across sync.
"""


def _ordered_entry(entry: dict[str, Any]) -> dict[str, Any]:
    """Return a single entry with canonical key order and inline rendering hints applied."""
    out: dict[str, Any] = {}
    for key in ENTRY_KEY_ORDER:
        if key not in entry:
            continue
        value = entry[key]
        if key in ("tags", "depends_on"):
            out[key] = _FlowSeq(value)
        elif key == "params":
            out[key] = {pname: _FlowMap(pval) if isinstance(pval, dict) else pval for pname, pval in value.items()}
        else:
            out[key] = value
    return out


def dump_yaml(entries: list[dict[str, Any]], path: Path) -> None:
    """Write ``entries`` to ``path`` as a YAML list with a descriptive header."""
    rendered = [_ordered_entry(e) for e in entries]
    body = yaml.dump(
        rendered,
        Dumper=_NotebooksDumper,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=4096,
    )
    path.write_text(HEADER + "\n" + body, encoding="utf-8")


def load_yaml(path: Path) -> list[dict[str, Any]]:
    """Load notebook entries from ``path``."""
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if data is None:
        return []
    if not isinstance(data, list):
        msg = f"Expected a top-level list in {path}, got {type(data).__name__}"
        raise ValueError(msg)
    return data


# --- sync / check / migrate ----------------------------------------------------------------


def _merge_entry(derived: dict[str, Any], existing: dict[str, Any] | None) -> dict[str, Any]:
    """Combine freshly derived fields with curated fields from an existing entry (or defaults)."""
    entry = dict(derived)
    for field, default in CURATED_DEFAULTS.items():
        if existing is not None and field in existing:
            entry[field] = existing[field]
        else:
            entry[field] = json.loads(json.dumps(default))  # deep copy of the default
    return entry


def sync(tutorials_dir: Path, yaml_path: Path) -> list[dict[str, Any]]:
    """Regenerate derived fields from notebooks, preserving curated fields, and write the file."""
    existing_by_path: dict[str, dict[str, Any]] = {}
    if yaml_path.exists():
        existing_by_path = {e["path"]: e for e in load_yaml(yaml_path) if isinstance(e, dict) and "path" in e}

    entries = [_merge_entry(d, existing_by_path.get(d["path"])) for d in build_derived_entries(tutorials_dir)]
    dump_yaml(entries, yaml_path)
    print(f"Wrote {len(entries)} notebook entries to {yaml_path}")
    return entries


def check(tutorials_dir: Path, yaml_path: Path) -> list[str]:
    """Return a list of human-readable drift problems; empty list means the file is up to date."""
    problems: list[str] = []

    if not yaml_path.exists():
        return [f"{yaml_path} does not exist (run `sync`)"]

    stored = load_yaml(yaml_path)
    stored_by_path = {e["path"]: e for e in stored if isinstance(e, dict) and "path" in e}
    stored_order = [e["path"] for e in stored if isinstance(e, dict) and "path" in e]

    fresh = build_derived_entries(tutorials_dir)
    fresh_by_path = {e["path"] for e in fresh}
    fresh_order = [e["path"] for e in fresh]

    for missing in fresh_order:
        if missing not in stored_by_path:
            problems.append(f"notebook not in notebooks.yaml: {missing} (run `sync`)")
    for extra in stored_order:
        if extra not in fresh_by_path:
            problems.append(f"notebooks.yaml entry has no matching notebook: {extra} (run `sync`)")

    if stored_order != fresh_order and sorted(stored_order) == sorted(fresh_order):
        problems.append("notebooks.yaml ordering differs from canonical traversal order (run `sync`)")

    for derived in fresh:
        existing = stored_by_path.get(derived["path"])
        if existing is None:
            continue
        for field in DERIVED_FIELDS:
            if existing.get(field) != derived[field]:
                problems.append(
                    f"{derived['path']}: derived field '{field}' is stale\n"
                    f"    in notebooks.yaml: {existing.get(field)!r}\n"
                    f"    from notebook:     {derived[field]!r}"
                )

    return problems


def _match_param_key_to_path(param_key: str, paths: list[str]) -> str | None:
    """Resolve a notebook_params.yaml key (a stem or partial path) to a full notebook path."""
    target = f"{param_key}.ipynb"
    exact = [p for p in paths if p == target or p.endswith(f"/{target}")]
    if len(exact) == 1:
        return exact[0]
    if len(exact) > 1:
        print(f"Warning: param key '{param_key}' matches multiple notebooks: {exact}", file=sys.stderr)
        return None
    by_stem = [p for p in paths if Path(p).stem == param_key]
    if len(by_stem) == 1:
        return by_stem[0]
    if len(by_stem) > 1:
        print(f"Warning: param key '{param_key}' matches multiple notebook stems: {by_stem}", file=sys.stderr)
    else:
        print(f"Warning: param key '{param_key}' matches no notebook", file=sys.stderr)
    return None


def migrate(
    tutorials_dir: Path,
    notebooks_json: Path,
    notebook_params_yaml: Path,
    yaml_path: Path,
) -> list[dict[str, Any]]:
    """One-shot build of notebooks.yaml from the legacy notebooks.json + notebook_params.yaml."""
    legacy = json.loads(notebooks_json.read_text(encoding="utf-8"))
    legacy_by_path = {e["path"]: e for e in legacy if isinstance(e, dict) and "path" in e}

    raw_params = yaml.safe_load(notebook_params_yaml.read_text(encoding="utf-8")) or {}

    derived_entries = build_derived_entries(tutorials_dir)
    all_paths = [d["path"] for d in derived_entries]

    # Resolve param keys -> full paths.
    params_by_path: dict[str, dict[str, Any]] = {}
    for param_key, params in raw_params.items():
        resolved = _match_param_key_to_path(param_key, all_paths)
        if resolved is not None:
            params_by_path[resolved] = params

    entries: list[dict[str, Any]] = []
    for derived in derived_entries:
        path = derived["path"]
        legacy_entry = legacy_by_path.get(path, {})
        entry = dict(derived)
        entry["include_in_docs"] = legacy_entry.get("include_in_docs", CURATED_DEFAULTS["include_in_docs"])
        entry["include_in_tests"] = legacy_entry.get("include_in_tests", CURATED_DEFAULTS["include_in_tests"])
        entry["include_in_public_examples"] = legacy_entry.get(
            "include_in_public_examples", CURATED_DEFAULTS["include_in_public_examples"]
        )
        entry["params"] = params_by_path.get(path, {})
        entry["depends_on"] = []
        entries.append(entry)

    dump_yaml(entries, yaml_path)

    matched = sum(1 for p in params_by_path)
    print(f"Migrated {len(entries)} notebooks to {yaml_path}")
    print(f"  legacy notebooks.json entries: {len(legacy_by_path)}")
    print(f"  param keys resolved: {matched}/{len(raw_params)}")
    return entries


# --- CLI -----------------------------------------------------------------------------------


def _default_tutorials_dir() -> Path:
    return Path(__file__).resolve().parent.parent / "tutorials"


def main() -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)

    default_tutorials = _default_tutorials_dir()
    default_yaml = default_tutorials / "notebooks.yaml"

    p_sync = sub.add_parser("sync", help="Regenerate derived fields, preserving curated fields")
    p_sync.add_argument("--tutorials-dir", type=Path, default=default_tutorials)
    p_sync.add_argument("--yaml", type=Path, default=default_yaml)

    p_check = sub.add_parser("check", help="Fail if derived fields drift from notebook content")
    p_check.add_argument("--tutorials-dir", type=Path, default=default_tutorials)
    p_check.add_argument("--yaml", type=Path, default=default_yaml)

    p_migrate = sub.add_parser("migrate", help="One-shot build from legacy notebooks.json + notebook_params.yaml")
    p_migrate.add_argument("--tutorials-dir", type=Path, default=default_tutorials)
    p_migrate.add_argument("--yaml", type=Path, default=default_yaml)
    p_migrate.add_argument("--notebooks-json", type=Path, required=True)
    p_migrate.add_argument("--notebook-params", type=Path, default=default_tutorials / "notebook_params.yaml")

    args = parser.parse_args()

    if args.command == "sync":
        sync(args.tutorials_dir, args.yaml)
        return 0
    if args.command == "check":
        problems = check(args.tutorials_dir, args.yaml)
        if problems:
            print(f"notebooks.yaml is out of date ({len(problems)} problem(s)):\n", file=sys.stderr)
            for problem in problems:
                print(f"  - {problem}", file=sys.stderr)
            print("\nRun `python -m utils.notebooks_metadata sync` to fix.", file=sys.stderr)
            return 1
        print("notebooks.yaml is up to date with notebook content.")
        return 0
    if args.command == "migrate":
        migrate(args.tutorials_dir, args.notebooks_json, args.notebook_params, args.yaml)
        return 0

    return 2


if __name__ == "__main__":
    sys.exit(main())
